default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40531_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40531_test

production:
  <<: *default
  database: furima_40531_production
  username: furima_40531
  password: <%= ENV["DATABASE_PASSWORD"] %>
